### ISSUE TITLE
Weekly Digest v1.0.0 Release Checklist

### ISSUE THREAD

**Issue by abhijeetps** [probot/weekly-digest#31]
Here, I am preparing a checklist for public release of Weekly Digest v1.0.0.
The checklist contains jobs to be completed before v1.0.0 release.

- [x] Refactor Codes
  - [x] _index.js_
  - [x] _weeklyDigest.js_
  - [x] _getAllIssues.js_
  - [x] _getAllPullRequests.js_
  - [x] _getCommits.js_
  - [x] _getContributor.js_
  - [x] _getReleases.js_
  - [x] _getSearchIssues.js_
  - [x] _getStargazers.js_
  - [x] _postCreateIssues.js_
  - [x] _postCreateLabel.js_
  - [x] _checkDuplicates.js_
  - [x] _defaultConfig.js_
  - [x] _fixConfig.js_
  - [x] _getDate.js_
  - [x] _getLongMonth.js_
  - [x] _getNumDayFromLongDay.js_
  - [x] _markdownBody.js_
  - [x] _markdownCommits.js_
  - [x] _markdownContributors.js_
  - [x] _markdownIssues.js_
  - [x] _markdownPullRequests.js_
  - [x] _markdownReleases.js_
  - [x] _markdownStargazers.js_

- [x] Add more tests 
  - [x] _index.test.js_
  - [x] _weeklyDigest.test.js_
  - [x] _getAllIssues.test.js_
  - [x] _getAllPullRequests.test.js_
  - [x] _getCommits.test.js_
  - [x] _getContributor.test.js_
  - [x] _getReleases.test.js_
  - [x] _getSearchIssues.test.js_
  - [x] _getStargazers.test.js_
  - [x] _postCreateIssues.test.js_
  - [x] _postCreateLabel.test.js_
  - [x] _checkDuplicates.test.js_
  - [x] _defaultConfig.test.js_
  - [x] _fixConfig.test.js_
  - [x] _getDate.test.js_
  - [x] _getLongMonth.test.js_
  - [x] _getNumDayFromLongDay.test.js_
  - [x] _markdownBody.test.js_
  - [x] _markdownCommits.test.js_
  - [x] _markdownContributors.test.js_
  - [x] _markdownIssues.test.js_
  - [x] _markdownPullRequests.test.js_
  - [x] _markdownReleases.test.js_
  - [x] _markdownStargazers.test.js_

- [x] Code Coverage 💯 
- [x] Paginate 🔢 
- [x] Deploy to now.sh 🚢 
- [x] Sentry 🐛 
- [x] Update README.md 📓 

- [x] Blog ✍️ 
- [x] Share 🎉 
- [x] Tweet 🐦
